# Conditional MC of Heston Model based on QE Scheme

## QE Discretization Scheme for Heston Model 

<font color=black size=3 face=times>**Main references**: <br>
         Andersen, L. (2008). Simple and efficient simulation of the Heston stochastic volatility model. *The Journal of Computational Finance, 11*(3), 1–42. https://doi.org/10.21314/JCF.2008.189 <br>
        Van Haastrecht, A., & Pelsser, A. (2010). Efficient, almost exact simulation of the heston stochastic volatility model. *International Journal of Theoretical and Applied Finance, 13*(01), 1–43. https://doi.org/10.1142/S0219024910005668 <br>

<font color=black size=3 face=times>**1.1. Notation declaration**<br>
The SDE of Heston model expressed by:
    <br/>
    \begin{align*}
    &dX(t)/X(t)=\sqrt{V(t)}dW_X(t) ,\\
    &dV(t)=\kappa(\theta-V(t))dt+\epsilon\sqrt{V(t)}dW_V(t),
    \end{align*} 
- $W_X$ and $W_V$ are scalar Brownian motions in some probability measure and assume that $dW_X(t)\dot dW_Y(t)=\rho dt$  
- $\widehat{X}$ and $\widehat{V}$ denote discrete-time approximations to $X$ and $V$, i.e. The basic **Euler Scheme** would take the form:
 \begin{align*}
    ln\widehat{X}(t+\Delta)&=ln\widehat{X}(t)-\frac{1}{2}\widehat{V}(t)\Delta+\sqrt{\widehat{V}(t)}Z_X\sqrt{\Delta} ,\\
    ln\widehat{V}(t+\Delta)&=\widehat{V}(t)+\kappa(\theta-\widehat{V}(t))\Delta+\epsilon\sqrt{\widehat{V}(t)}Z_V\sqrt{\Delta},
    \end{align*}  
- $V(t),V(t+\Delta)$ are sampled directly from the known conditional distribution of $V(t)$ and $lnX(t),lnX(t+\Delta)$ are from Gaussian distribution. 

<font color=black size=3 face=times>**1.2. General discrete-time approximation schemes**<br>
    &emsp;&emsp;<font color=black size=3 face=times>**Kahl-Jackel Scheme**<br>
    &emsp;&emsp;Using Milstein scheme to discretize the V-process and "IJK" discretization for the stock process:
    \begin{align*}
    ln\widehat{X}(t+\Delta)&=ln\widehat{X}(t)-\frac{\Delta}{4}(\widehat{V}(t+\Delta)+\widehat{V}(t))+\rho\sqrt{\widehat{V}(t)}Z_V\sqrt{\Delta}+\frac{1}{2}\left(\sqrt{\widehat{V}(t+\Delta)}+\sqrt{\widehat{V}(t)}\right)(Z_X\sqrt{\Delta}-\rho Z_V\sqrt{\Delta})+\frac{1}{4}\epsilon\rho\Delta(Z_V^2-1),\tag{$1.1$}\\
    \widehat{V}(t+\Delta) &= \frac{\widehat{V}(t)+\kappa\theta\Delta+\epsilon\sqrt{\widehat{V}(t)}Z_V\sqrt{\Delta}+\frac{1}{4}\epsilon^2\Delta(Z_V^2-1)}{1+\kappa\Delta}, \tag{$1.2$}
    \end{align*}
    <br/>
    &emsp;&emsp;<font color=black size=3 face=times>**Broadie-Kaya Scheme**<br>
\begin{align*}
    V(t+\Delta)&=V(t)+\int_{t}^{t+\Delta}\kappa(\theta-V(u))du+\epsilon \int_{t}^{t+\Delta}\sqrt{V(u)}dW_V(u) ,\tag{$1.3$}\\
    lnX(t+\Delta)&=lnX(t)+\frac{\rho}{\epsilon}(V(t+\Delta)-V(t)-\kappa\theta\Delta)+(\frac{\kappa\rho}{\epsilon}-\frac{1}{2})\int_{t}^{t+\Delta}V(u)du+\sqrt{1-\rho^2}\int_{t}^{t+\Delta}\sqrt{V(u)}dW(u), \tag{$1.4$}
    \end{align*}

<font color=black size=3 face=times>**1.3. TG Scheme**<br>
        &emsp;&emsp; The TG (Truncated Gaussian) Scheme writes
    $$\widehat{V}(t+\Delta)=(\mu+\sigma\dot Z_V)^{+},\tag{$1.5$}$$
    &emsp;&emsp; where $Z_V$ is a standart Gaussian random variable, and $\mu$ and $\sigma$ are constants that will depend on the time-step $\Delta$ and $\widehat{V}(t)$, as well as the parameters in the SDE for $V$.<br>
    &emsp;&emsp;Let:
    \begin{align*}
    m&=\theta+(\widehat{V}(t)-\theta)e^{-\kappa\Delta},\tag{$1.6$}\\
    s^2&=\frac{\widehat{V}(t)\epsilon^2 e^{-\kappa\Delta}}{\kappa}(1-e^{-\kappa\Delta})+\frac{\theta\epsilon^2}{2\kappa}(1-e^{-\kappa\Delta})^2,\tag{$1.7$}\\
    \Psi&\equiv s^2/m^2 =\frac{\frac{\widehat{V}(t)\epsilon^2 e^{-\kappa\Delta}}{\kappa}(1-e^{-\kappa\Delta})+\frac{\theta\epsilon^2}{2\kappa}(1-e^{-\kappa\Delta})^2}{(\theta+(\widehat{V}(t)-\theta)e^{-\kappa\Delta})^2}, \tag{$1.8$}
    \end{align*}
    &emsp;&emsp; Define the ratio $r=\mu/\sigma$, match the mean to $m$ results in:
    $$\mu=\frac{m}{r^{-1}\phi(r)+\Phi(r)};\quad \sigma=r^{-1}\mu=\frac{m}{\phi(r)+r\Phi(r)}$$
    &emsp;&emsp; where $\phi$ is pdf of normal distribution and $\Phi$ is cdf of normal distribution.
    \begin{align*}
    &\mu=f_{\mu}(\Psi)\cdot m,\quad f_{\mu}(\Psi)=\frac{r(\Psi)}{\phi(r(\Psi))+r(\Psi)\Phi(r(\Psi))},\tag{$1.9$}\\
    &\sigma=f_{\sigma}(\Psi)\cdot s,\quad f_{\sigma}(\Psi)=\frac{\Psi^{-1/2}}{\phi(r(\Psi))+r(\Psi)\Phi(r(\Psi))},\tag{$1.10$}
    \end{align*}
    &emsp;&emsp;The detailed algorithm for the TG simulation step from $\widehat{V}(t)$ to $\widehat{V}(t+\Delta)$ is as follows:<br>
    &emsp;&emsp;1.Given $\widehat{V}(t)$, compute $m$ and $s^2$ from (1.6) and (1.7).<br>
    &emsp;&emsp;2.Compute $\Psi=s^2/m^2$ and look up $f_{\mu}(\Psi)$ and $f_{\sigma}(\Psi)$ from cache<br>
    &emsp;&emsp;3.Compute $\mu$ and $\sigma$ according to equations (1.9) and (1.10)<br>
    &emsp;&emsp;4.Compute $Z_V=\Phi^{-1}(U_V)$<br>
    &emsp;&emsp;5.Set $\widehat{V}(t+\Delta)=(\mu+\sigma\dot Z_V)^{+}$

<font color=black size=3 face=times>**1.4. QE Scheme**<br>
    &emsp;&emsp; For the non-central chi-square distribution approaches a Gaussian distribution as the non-centrality paremeter approaches $\infty$, but for small $V(t)$, the non-centrality parameter approaches zero, and the Gaussian variable is typically not accurate.<br>
    &emsp;&emsp; For sufficiently large values of $\widehat{V}(t)$, we write:
    $$\widehat{V}(t+\Delta)=a(b+Z_V)^2,\tag{$1.11$}$$
    &emsp;&emsp; For low values of $\widehat{V}(t)$, we use asymptotic density and approximated density for $\widehat{V}(t+\Delta)$, we have the form:
        $$\Psi^{-1}(u)=\Psi^{-1}(u;p,\beta)=\left\{
\begin{aligned}
&0,  & 0\le u\le p \\
&\beta^{-1}ln(\frac{1-p}{1-u}),& p<u\le1.
\end{aligned},\tag{$1.12$}
\right.
$$
    &emsp;&emsp; The scheme varies when $\Psi$ is big and when $\Psi$ is small.<br>
    &emsp;&emsp; Assume that some arbitrary level $\Psi_c\in [1,2]$ has beem selected. The detailed algorithm for the QE simulation step from $\widehat{V}(t)$ to $\widehat{V}(t+\Delta)$ is then:<br>
    &emsp;&emsp;1. Given $\widehat{V}(t)$, compute $m$ and $s^2$ from the equations (1.6) and (1.7).<br>
    &emsp;&emsp;2. Compute $\Psi=s^2/m^2$<br>
    &emsp;&emsp;3. Draw a uniform random number $U_V$<br>
    &emsp;&emsp;4. **If** $\Psi\leq \Psi_c$:<br>
    &emsp;&emsp;&emsp;&emsp;(a) Compute a and b as:
    \begin{align*}
    &b^2=2\Psi^{-1}-1+\sqrt{2\Psi^{-1}}\sqrt{{2\Psi^{-1}-1}}\ge 0,\tag{$1.13$}\\
    &a=\frac{m}{1+b^2},\tag{$1.14$}\\
    \end{align*}
    &emsp;&emsp;&emsp;&emsp;(b) Compute $Z_V=\Phi^{-1}(U_V)$<br>
    &emsp;&emsp;&emsp;&emsp;(c) Set $\widehat{V}(t+\Delta)=a(b+Z_V)^2$<br>
    &emsp;&emsp;5.**Otherwise**, if $\Psi>\Psi_c$:<br>
    &emsp;&emsp;&emsp;&emsp;(a) Compute $\beta$ and $p$ as:
    \begin{align*}
    &p=\frac{\Psi-1}{\Psi+1}\in [0,1),\tag{$1.15$}\\
    &\beta=\frac{1-p}{m}=\frac{2}{m(\Psi+1)}>0,\tag{$1.16$}\\
    \end{align*}
    &emsp;&emsp;&emsp;&emsp;(b) Set $\widehat{V}(t+\Delta)=\Psi^{-1}(U_V;p,\beta)$, where $\Psi^{-1}$ is given at (1.12)<br>
    &emsp;&emsp; After simulating the path, calculate:
\begin{align*}
     E\left(S_T|V(T),\int V(t)dt\right)&=S_0 exp\left(\frac{\rho}{\nu}(V(T)-V(0))-\kappa(\theta-\int_{0}^{T}V(t)dt)\right),\tag{$1.17$}\\
     \sigma&=\left((1-\rho^2)\int_{0}^{T}V(t)dt\right)^{\frac{1}{2}},\tag{$1.18$}\\
    \end{align*}
    &emsp;&emsp; Then bring the Forward price and volatility into the bsm option pricing model.

In [2]:
import numpy as np
import heston_cmc_qe as heston
import time
import pyfeng as pf
import matplotlib.pyplot as plt
from tqdm import tqdm

## Andersen's (2008) and Van's (2010) examples, with multiple strikes and single spot

In [3]:
# Examples
# Andersen (2008)
strike = [100.0, 140.0, 70.0]
forward = 100
delta = [1, 1/2, 1/4, 1/8, 1/16, 1/32]
case = np.zeros([3, 7])
#case[i]=[vov, kappa, rho, texp, theta,  sigma,     r]
case[0] = [1,   0.5, -0.9, 10, 0.04, np.sqrt(0.04), 0]
case[1] = [0.9, 0.3, -0.5, 15, 0.04, np.sqrt(0.04), 0]
case[2] = [1,   1,   -0.3, 5,  0.09, np.sqrt(0.09), 0]

In [4]:
# Van (2010)
strike = [100.0, 140.0, 60.0]
forward = 100
delta = [1, 1/2, 1/4, 1/8, 1/16, 1/32]
case = np.zeros([3, 7])
#case[i]=[vov, kappa, rho, texp, theta,   sigma,    r]
case[0] = [1,   0.5, -0.9, 10, 0.04, np.sqrt(0.04), 0]
case[1] = [1,   1,   -0.3, 5,  0.09, np.sqrt(0.09), 0.05]
case[2] = [0.9, 0.3, -0.5, 15, 0.04, np.sqrt(0.04), 0]
ref_price = np.array([[13.085, 0.296, 44.330], [33.597, 18.157, 56.575], [16.649, 5.138, 45.287]])

In [5]:
price_cmc = np.zeros([case.shape[0], len(delta), len(strike)])
bias_cmc = np.zeros_like(price_cmc)

### Compute conditional MC price and bias

In [4]:
# compute conditional mc price and bias
# for cases with multiple strike and single forward
for i in range(case.shape[0]):
    vov, kappa, rho, texp, theta, sigma, r = case[i]
    
    start = time.time()
    heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)
    
    for d in range(len(delta)):
        price_cmc[i, d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e5, seed=123456)
        bias_cmc[i, d, :] = price_cmc[i, d, :] - ref_price[i, :]

    end = time.time()
    
    print('Case %s:' % i)
    np.set_printoptions(suppress=True)
    print('computed price')
    print(price_cmc[i, :, :])

    print('bias')
    print(bias_cmc[i, :, :])
    print('Running time is %.3f seconds.' % (end - start) + '\n')

Case 0:
computed price
[[14.52722285  0.19584722 45.56885919]
 [13.56691261  0.26568546 44.54763058]
 [13.22061601  0.29003533 44.38373889]
 [13.12057087  0.29501411 44.38517817]
 [13.1042753   0.29476289 44.37643641]
 [13.09047939  0.29547721 44.34474341]]
bias
[[ 1.44222285 -0.10015278  1.23885919]
 [ 0.48191261 -0.03031454  0.21763058]
 [ 0.13561601 -0.00596467  0.05373889]
 [ 0.03557087 -0.00098589  0.05517817]
 [ 0.0192753  -0.00123711  0.04643641]
 [ 0.00547939 -0.00052279  0.01474341]]
Running time is 127.637 seconds.

Case 1:
computed price
[[33.70110363 17.46225376 56.87045054]
 [33.68732515 17.80206579 56.71721154]
 [33.61087184 18.07626695 56.55693734]
 [33.58706642 18.13154399 56.5519081 ]
 [33.58468734 18.13728253 56.56606366]
 [33.60527156 18.16620125 56.58439142]]
bias
[[ 0.10410363 -0.69474624  0.29545054]
 [ 0.09032515 -0.35493421  0.14221154]
 [ 0.01387184 -0.08073305 -0.01806266]
 [-0.00993358 -0.02545601 -0.0230919 ]
 [-0.01231266 -0.01971747 -0.00893634]
 [ 0.00827

When path=1e6, computation is time-consuming (especially for texp=15), separate the three cases to get stable computation

In [5]:
i = 0
vov, kappa, rho, texp, theta, sigma, r = case[i]

start = time.time()
heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)

for d in range(len(delta)):
    price_cmc[i, d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e6, seed=123456)
    bias_cmc[i, d, :] = price_cmc[i, d, :] - ref_price[i, :]

end = time.time()

print('Case %s:' % i)
np.set_printoptions(suppress=True)
print('computed price')
print(price_cmc[i, :, :])

print('bias')
print(bias_cmc[i, :, :])
print('Running time is %.3f seconds.' % (end - start) + '\n')

Case 0:
computed price
[[14.52988166  0.1954481  45.5566836 ]
 [13.58264697  0.26538629 44.59576156]
 [13.18875382  0.29164219 44.35693654]
 [13.09245767  0.29643382 44.32630416]
 [13.09234981  0.29612097 44.3554616 ]
 [13.0747208   0.29571157 44.30422413]]
bias
[[ 1.44488166 -0.1005519   1.2266836 ]
 [ 0.49764697 -0.03061371  0.26576156]
 [ 0.10375382 -0.00435781  0.02693654]
 [ 0.00745767  0.00043382 -0.00369584]
 [ 0.00734981  0.00012097  0.0254616 ]
 [-0.0102792  -0.00028843 -0.02577587]]
Running time is 1239.845 seconds.



In [6]:
i = 1
vov, kappa, rho, texp, theta, sigma, r = case[i]

start = time.time()
heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)

for d in range(len(delta)):
    price_cmc[i, d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e6, seed=123456)
    bias_cmc[i, d, :] = price_cmc[i, d, :] - ref_price[i, :]

end = time.time()

print('Case %s:' % i)
np.set_printoptions(suppress=True)
print('computed price')
print(price_cmc[i, :, :])

print('bias')
print(bias_cmc[i, :, :])
print('Running time is %.3f seconds.' % (end - start) + '\n')

Case 1:
computed price
[[33.73639816 17.45658862 56.93686071]
 [33.6862614  17.7939801  56.72279494]
 [33.62950685 18.06468289 56.61902551]
 [33.60258667 18.14381343 56.57858711]
 [33.59659541 18.15261599 56.57703292]
 [33.59741061 18.15529961 56.5780489 ]]
bias
[[ 0.13939816 -0.70041138  0.36186071]
 [ 0.0892614  -0.3630199   0.14779494]
 [ 0.03250685 -0.09231711  0.04402551]
 [ 0.00558667 -0.01318657  0.00358711]
 [-0.00040459 -0.00438401  0.00203292]
 [ 0.00041061 -0.00170039  0.0030489 ]]
Running time is 681.720 seconds.



In [7]:
# take quite a long time to compute
i = 2
vov, kappa, rho, texp, theta, sigma, r = case[i]

start = time.time()
heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)

for d in range(len(delta)):
    price_cmc[i, d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e6, seed=123456)
    bias_cmc[i, d, :] = price_cmc[i, d, :] - ref_price[i, :]

end = time.time()

print('Case %s:' % i)
np.set_printoptions(suppress=True)
print('computed price')
print(price_cmc[i, :, :])

print('bias')
print(bias_cmc[i, :, :])
print('Running time is %.3f seconds.' % (end - start) + '\n')

KeyboardInterrupt: 

### Compute std error of conditional MC price

In [8]:
n = 50
for i in range(case.shape[0]):
    start = time.time()
    vov, kappa, rho, texp, theta, sigma, r = case[i]

    heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)
    price_cmc = np.zeros([n, len(delta), len(strike)])
    for j in tqdm(range(n)):
        for d in range(len(delta)):
            price_cmc[j, d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e4)
            
    end = time.time()
    print('Case %s:' % i)
    print('computed price')
    print(price_cmc.mean(axis=0))
    print('std error of conditional MC')
    print(price_cmc.std(axis=0))
    print('Running time is %.3f seconds.' % (end - start) + '\n')

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [08:15<00:00,  9.92s/it]


Case 0:
computed price
[[14.5203858   0.19509451 45.52203955]
 [13.58136981  0.26529004 44.59468135]
 [13.19609127  0.29187395 44.37059131]
 [13.09018819  0.29703984 44.33355136]
 [13.07406605  0.29696865 44.32439902]
 [13.09832797  0.29585805 44.37110991]]
std error of conditional MC
[[0.08852271 0.00213495 0.21807294]
 [0.08330737 0.00297587 0.19164552]
 [0.09267493 0.00287989 0.2265294 ]
 [0.07733342 0.00215729 0.20412114]
 [0.08064352 0.00247084 0.21281211]
 [0.0833296  0.00249145 0.20760677]]
Running time is 496.367 seconds.



100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [04:29<00:00,  5.39s/it]


Case 1:
computed price
[[33.73147729 17.46024923 56.91830707]
 [33.66953472 17.78586023 56.68978114]
 [33.61313031 18.05692271 56.59042084]
 [33.6088894  18.13794643 56.59842828]
 [33.60424631 18.161567   56.58718949]
 [33.59115304 18.16558111 56.55645369]]
std error of conditional MC
[[0.04781501 0.03737528 0.10749406]
 [0.05483284 0.0346728  0.12074765]
 [0.05173381 0.04028025 0.12492807]
 [0.0524559  0.03855589 0.10787887]
 [0.05449511 0.03000034 0.11958618]
 [0.05609015 0.04441259 0.12018084]]
Running time is 269.295 seconds.



100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [12:41<00:00, 15.24s/it]


Case 2:
computed price
[[16.1383193   4.76316836 45.52326353]
 [16.44624442  5.06940902 45.35128819]
 [16.60917412  5.14335922 45.29290186]
 [16.64953119  5.14682309 45.2867721 ]
 [16.66243944  5.1412643  45.31990055]
 [16.65227454  5.14796606 45.26376083]]
std error of conditional MC
[[0.04599494 0.05836611 0.10952485]
 [0.03766147 0.05338242 0.10951823]
 [0.03722262 0.04141417 0.1002134 ]
 [0.04465307 0.04900011 0.09765122]
 [0.04190097 0.04429235 0.11276059]
 [0.04286761 0.04579411 0.0936633 ]]
Running time is 762.000 seconds.



### Compare the model with {Conditional MC with TG/Euler Scheme, Exact MC, Almost Exact MC}

In [6]:
# from comparison import heston_exact
from comparison import heston_ae as heston_mc_ae

In [7]:
delta = 1/32
path = int(1e4)
n_comp = 5
price_comp = np.zeros([n_comp, case.shape[0], len(strike)])
bias_comp = np.zeros_like(price_comp)

In [10]:
for i in range(case.shape[0]):
    vov, kappa, rho, texp, theta, sigma, r = case[i]
    
    start = time.time()
    heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)
    heston_ae = heston_mc_ae.HestonMCAe(vov, kappa, rho, theta, r)
#     heston_exact = 
    
    price_comp[0, i, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta, intr=r, path=path, seed=123456, scheme='QE')
    bias_comp[0, i, :] = price_comp[0, i, :] - ref_price[i, :]
    
    price_comp[1, i, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta, intr=r, path=path, seed=123456, scheme='TG')
    bias_comp[1, i, :] = price_comp[1, i, :] - ref_price[i, :]
    
    price_comp[2, i, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta, intr=r, path=path, seed=123456, scheme='Euler')
    bias_comp[2, i, :] = price_comp[2, i, :] - ref_price[i, :]
    
    price_comp[3, i, :]= heston_exact.price()
    bias_comp[3, i, :] = price_comp[3, i, :] - ref_price[i, :]
    
    price_comp[4, i, :]= heston_ae.price(strike, forward, texp, sigma, n_paths=int(path), intr=0, divr=0)
    bias_comp[4, i, :] = price_comp[4, i, :] - ref_price[i, :]

    end = time.time()
    
    print('Case %s:' % i)
    np.set_printoptions(suppress=True)

    print('CMC (QE scheme)')
    print(bias_comp[0, i, :])
    print('CMC (TG scheme)')
    print(bias_comp[1, i, :])
    print('CMC (Euler scheme)')
    print(bias_comp[2, i, :])
#     print('Exact MC')
#     print(bias_comp[3, i, :])
    print('AE MC')
    print(bias_comp[4, i, :])
    print('Running time is %.3f seconds.' % (end - start) + '\n')

Case 0:
CMC (QE scheme)
[-0.09658033  0.00003062 -0.23903261]
CMC (TG scheme)
[0. 0. 0.]
CMC (Euler scheme)
[0. 0. 0.]
AE MC
[5.67005914 2.07486465 2.74478433]
Running time is 0.137 seconds.

Case 1:
CMC (QE scheme)
[0. 0. 0.]
CMC (TG scheme)
[0. 0. 0.]
CMC (Euler scheme)
[0. 0. 0.]
AE MC
[13.85517292 11.14383076 17.56122643]
Running time is 0.134 seconds.

Case 2:
CMC (QE scheme)
[0. 0. 0.]
CMC (TG scheme)
[0. 0. 0.]
CMC (Euler scheme)
[0. 0. 0.]
AE MC
[7.12829839 5.5886318  3.05904935]
Running time is 0.130 seconds.



In [ ]:
# exact mc to be added

## Von's (2008) example, with multiple spots and single strike

In [ ]:
# Example
# Von (2018), multiple forward, single strike
strike = [100.0]
forward = [75, 100, 125]
delta = [1, 1/2, 1/4, 1/8, 1/16, 1/32]
case = np.zeros([3, 7])
vov = 1
kappa = 2.58
rho = -0.36
texp = 1
theta = 0.043
sigma = np.sqrt(0.114)
r = 0
ref_price = np.array([0.908502728459621, 9.046650119220969, 28.514786399298796])

In [ ]:
# compute conditional mc price and bias
# for cases with single strike and multiple forward
price_cmc = np.zeros([len(delta), len(forward)])
bias_cmc = np.zeros([len(delta), len(forward)])
start = time.time()
for i in range(len(forward)):
    heston_cmc_qe = heston.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)
    
    for d in range(len(delta)):
        price_cmc[d, i] = heston_cmc_qe.price(strike, forward[i], texp, sigma=sigma, delta=delta[d], intr=r, path=1e6, seed=123456)
        bias_cmc[d, i] = price_cmc[d, i] - ref_price[i]

end = time.time()
np.set_printoptions(suppress=True)
print('price:')
print(price_cmc)
print('bias:')
print(bias_cmc)
print('Running time is %.3f seconds.' % (end - start) + '\n')